name: Callable — Release Please

on:
  workflow_call:
    inputs:
      release_branch:
        type: string
        required: true
      release_type:
        type: string
        required: true
      package_name:
        type: string
        required: false
        default: ''
      bootstrap_sha:
        type: string
        required: false
        default: ''
    secrets:
      NPM_AUTH_TOKEN:
        required: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          target-branch: ${{ inputs.release_branch }}
          release-type: ${{ inputs.release_type }}
          package-name: ${{ inputs.package_name }}
          bootstrap-sha: ${{ inputs.bootstrap_sha }}
